server:
  port: 56030

spring:
  application:
    name: local-service
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848

dubbo:
  scan:
  #dubbo 服务扫描基准包
    base-packages: com.taikang
  protocol:
  #dubbo 协议
    name: dubbo
    #dubbo 协议端口
    port: -1
  registry:
    address: nacos://127.0.0.1:8848
  application:
    qos-enable: false #dubbo运维服务是否开启
  consumer:
    check: false  #启动时就否检查依赖的服务



test:
  name: LOCAL-SERVICE


  sentinel:
    eager: true # 是否饥饿加载。默认为 false 关闭
    transport:
      dashboard: localhost:7070 # 是否饥饿加载。
    # Sentinel 对 Spring Cloud Gateway 的专属配置项，对应 SentinelGatewayProperties 类
    scg:
      order: -2147483648 # 过滤器顺序，默认为 -2147483648 最高优先级
      fallback:
        mode: # fallback 模式，目前有三种：response、redirect、空
        # 专属 response 模式
        response-status: 429 # 响应状态码，默认为 429
        response-body: 你被 block 了... # 响应内容，默认为空
        content-type: application/json # 内容类型，默认为 application/json
